baseURL = "https://shuangli.github.io/"
languageCode = "en-us"
title = "Shuang Li"
theme = "zero-academic-page"

[params]
  author = "Shuang Li"
  description = "Ph.D. Candidate in Software Engineering at Wuhan University"
  email = "shuangli.cs@whu.edu.cn"
