[en]
languageName = 'English'
weight = 1
title = 'Zero'

[en.params]
    author = "LI Shuang"
    description = "Ph.D Student in [Wuhan University]. Focusing on the Performance of the LLM-generated code."

[[en.menu.main]]
    name = 'About Me'
    url = '#about-me'
    weight = 1
[[en.menu.main]]
    name = 'Publications'
    url = '#publications'
    weight = 3
[[en.menu.main]]
    name = 'Honors and Awards'
    url = '#honors-and-awards'
    weight = 4
[[en.menu.main]]
    name = 'Educations'
    url = '#educations'
    weight = 5
    
[zh]
languageName = '中文'
weight = 2
title = '学术主页'

[zh.params]
    author = "李爽"
    description = "武汉大学在读博士生，专注于大模型生成代码性能测试与优化"

[[zh.menu.main]]
    name = '关于我'
    url = '#about-me'
    weight = 1
[[zh.menu.main]]
    name = '发表论文'
    url = '#publications'
    weight = 3
[[zh.menu.main]]
    name = '荣誉与奖项'
    url = '#honors-and-awards'
    weight = 4
[[zh.menu.main]]
    name = '教育背景'
    url = '#educations'
    weight = 5
