profilePicture = "images/profile.jpg"
enableDarkMode = true

# Google Analytics ID, leave empty if you don't want to use Google Analytics
googleAnalyticsID = ""


[[social]]
name = "google-scholar"
url = "https://scholar.google.com/citations?user=tvtg5PUAAAAJ&hl=zh-CN&oi=sra"
icon = "fab fa-google-scholar"

[[social]]
name = "email"
url = "shuangli-cs@whu.edu.cn"
icon = "fas fa-envelope"
